oEditor.CreatePolyline Array("NAME:PolylineParameters", "IsPolylineCovered:=", true, "IsPolylineClosed:=",  _  true, Array("NAME:PolylinePoints", Array("NAME:PLPoint", "X:=", "$gh", "Y:=", "$td", "Z:=",  _  "0um"), Array("NAME:PLPoint", "X:=", "$gh+$ws", "Y:=", "$td", "Z:=", "0um"), Array("NAME:PLPoint", "X:=",  _  "$gh+$ws", "Y:=", "$td", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=", "$gh", "Y:=",  _  "$td", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=", "$gh", "Y:=", "$td", "Z:=", "0um")), Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 0, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 1, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 2, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 3, "NoOfPoints:=", 2)), Array("NAME:PolylineXSection", "XSectionType:=",  _  "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0um", "XSectionTopWidth:=",  _  "0um", "XSectionHeight:=", "0um", "XSectionNumSegments:=", "0", "XSectionBendType:=",  _  "Corner")), Array("NAME:Attributes", "Name:=", "Pos_sig", "Flags:=", "", "Color:=",  _  "(128 64 0)", "Transparency:=", 0.1, "PartCoordinateSystem:=", "Global", "UDMId:=",  _  "", "IsAlwaysHiden:=", false, "MaterialValue:=", "" & Chr(34) & "copper" & Chr(34) & "", "SolveInside:=",  _  true)oEditor.SweepAlongVector Array("NAME:Selections", "Selections:=", "Pos_sig", "NewPartsModelFlag:=",  _  "UseSourcePart"), Array("NAME:VectorSweepParameters", "DraftAngle:=", "0deg", "DraftType:=",  _  "Natural", "CheckFaceFaceIntersection:=", false, "SweepVectorX:=", "0um", "SweepVectorY:=",  _  "$tm1", "SweepVectorZ:=", "0um")oEditor.CreatePolyline Array("NAME:PolylineParameters", "IsPolylineCovered:=", true, "IsPolylineClosed:=",  _  true, Array("NAME:PolylinePoints", Array("NAME:PLPoint", "X:=", "$gh+$ws+$gg", "Y:=",  _  "$td", "Z:=", "0um"), Array("NAME:PLPoint", "X:=", "$gh+$ws+$gg+$wg1", "Y:=", "$td", "Z:=",  _  "0um"), Array("NAME:PLPoint", "X:=", "$gh+$ws+$gg+$wg1", "Y:=", "$td", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=",  _  "$gh+$ws+$gg", "Y:=", "$td", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=",  _  "$gh+$ws+$gg", "Y:=", "$td", "Z:=", "0um")), Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 0, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 1, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 2, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 3, "NoOfPoints:=", 2)), Array("NAME:PolylineXSection", "XSectionType:=",  _  "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0um", "XSectionTopWidth:=",  _  "0um", "XSectionHeight:=", "0um", "XSectionNumSegments:=", "0", "XSectionBendType:=",  _  "Corner")), Array("NAME:Attributes", "Name:=", "Pos_gnd", "Flags:=", "", "Color:=",  _  "(128 64 0)", "Transparency:=", 0.1, "PartCoordinateSystem:=", "Global", "UDMId:=",  _  "", "IsAlwaysHiden:=", false, "MaterialValue:=", "" & Chr(34) & "copper" & Chr(34) & "", "SolveInside:=",  _  true)oEditor.SweepAlongVector Array("NAME:Selections", "Selections:=", "Pos_gnd", "NewPartsModelFlag:=",  _  "UseSourcePart"), Array("NAME:VectorSweepParameters", "DraftAngle:=", "0deg", "DraftType:=",  _  "Natural", "CheckFaceFaceIntersection:=", false, "SweepVectorX:=", "0um", "SweepVectorY:=",  _  "$tm1", "SweepVectorZ:=", "0um")oEditor.CreatePolyline Array("NAME:PolylineParameters", "IsPolylineCovered:=", true, "IsPolylineClosed:=",  _  true, Array("NAME:PolylinePoints", Array("NAME:PLPoint", "X:=", "$g2", "Y:=",  _  "$td-$dm21-$tm2", "Z:=", "0um"), Array("NAME:PLPoint", "X:=", "$gh+$ws+$gg+$wg1", "Y:=",  _  "$td-$dm21-$tm2", "Z:=", "0um"), Array("NAME:PLPoint", "X:=", "$gh+$ws+$gg+$wg1", "Y:=",  _  "$td-$dm21-$tm2", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=", "$g2", "Y:=",  _  "$td-$dm21-$tm2", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=", "$g2", "Y:=",  _  "$td-$dm21-$tm2", "Z:=", "0um")), Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 0, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 1, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 2, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 3, "NoOfPoints:=", 2)), Array("NAME:PolylineXSection", "XSectionType:=",  _  "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0um", "XSectionTopWidth:=",  _  "0um", "XSectionHeight:=", "0um", "XSectionNumSegments:=", "0", "XSectionBendType:=",  _  "Corner")), Array("NAME:Attributes", "Name:=", "Pos_gnd_2", "Flags:=", "", "Color:=",  _  "(128 64 0)", "Transparency:=", 0.1, "PartCoordinateSystem:=", "Global", "UDMId:=",  _  "", "IsAlwaysHiden:=", false, "MaterialValue:=", "" & Chr(34) & "copper" & Chr(34) & "", "SolveInside:=",  _  true)oEditor.SweepAlongVector Array("NAME:Selections", "Selections:=", "Pos_gnd_2", "NewPartsModelFlag:=",  _  "UseSourcePart"), Array("NAME:VectorSweepParameters", "DraftAngle:=", "0deg", "DraftType:=",  _  "Natural", "CheckFaceFaceIntersection:=", false, "SweepVectorX:=", "0um", "SweepVectorY:=",  _  "$tm2", "SweepVectorZ:=", "0um")oEditor.CreatePolyline Array("NAME:PolylineParameters", "IsPolylineCovered:=", true, "IsPolylineClosed:=",  _  true, Array("NAME:PolylinePoints", Array("NAME:PLPoint", "X:=", "0um", "Y:=", "0um", "Z:=",  _  "0um"), Array("NAME:PLPoint", "X:=", "$gh+$ws+$gg+$wg1", "Y:=", "0um", "Z:=", "0um"), Array("NAME:PLPoint", "X:=",  _  "$gh+$ws+$gg+$wg1", "Y:=", "0um", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=", "0um", "Y:=",  _  "0um", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=", "0um", "Y:=", "0um", "Z:=", "0um")), Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 0, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 1, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 2, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=",  _  "Line", "StartIndex:=", 3, "NoOfPoints:=", 2)), Array("NAME:PolylineXSection", "XSectionType:=",  _  "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0um", "XSectionTopWidth:=",  _  "0um", "XSectionHeight:=", "0um", "XSectionNumSegments:=", "0", "XSectionBendType:=",  _  "Corner")), Array("NAME:Attributes", "Name:=", "diel_1", "Flags:=", "", "Color:=",  _  "(127 204 229)", "Transparency:=", 0.9, "PartCoordinateSystem:=", "Global", "UDMId:=",  _  "", "IsAlwaysHiden:=", false, "MaterialValue:=", "" & Chr(34) & "XXXX_40N_LP_DLE6" & Chr(34) & "", "SolveInside:=",  _  true)oEditor.SweepAlongVector Array("NAME:Selections", "Selections:=", "diel_1", "NewPartsModelFlag:=",  _  "UseSourcePart"), Array("NAME:VectorSweepParameters", "DraftAngle:=", "0deg", "DraftType:=",  _  "Natural", "CheckFaceFaceIntersection:=", false, "SweepVectorX:=", "0um", "SweepVectorY:=",  _  "$td", "SweepVectorZ:=", "0um")oEditor.CreatePolyline Array("NAME:PolylineParameters", "IsPolylineCovered:=", true, "IsPolylineClosed:=",  _  true, Array("NAME:PolylinePoints", Array("NAME:PLPoint", "X:=", "0um", "Y:=", "-$aw", "Z:=",  _  "0um"), Array("NAME:PLPoint", "X:=", "$gh+$ws+$gg+$wg1", "Y:=", "-$aw", "Z:=", "0um"), Array("NAME:PLPoint", "X:=",  _  "$gh+$ws+$gg+$wg1", "Y:=", "-$aw", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=", "0um", "Y:=",  _  "-$aw", "Z:=", "$Lw"), Array("NAME:PLPoint", "X:=", "0um", "Y:=", "-$aw", "Z:=",  _  "0um")), Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=",  _  0, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=",  _  1, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=",  _  2, "NoOfPoints:=", 2), Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=",  _  3, "NoOfPoints:=", 2)), Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=",  _  "Auto", "XSectionWidth:=", "0um", "XSectionTopWidth:=", "0um", "XSectionHeight:=",  _  "0um", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner")), Array("NAME:Attributes", "Name:=",  _  "Univers", "Flags:=", "", "Color:=", "(120 110 100)", "Transparency:=", 0, "PartCoordinateSystem:=",  _  "Global", "UDMId:=", "", "IsAlwaysHiden:=", false, "MaterialValue:=", "" & Chr(34) & "vacuum" & Chr(34) & "", "SolveInside:=",  _  true)oEditor.SweepAlongVector Array("NAME:Selections", "Selections:=", "Univers", "NewPartsModelFlag:=",  _  "UseSourcePart"), Array("NAME:VectorSweepParameters", "DraftAngle:=", "0deg", "DraftType:=",  _  "Natural", "CheckFaceFaceIntersection:=", false, "SweepVectorX:=", "0um", "SweepVectorY:=",  _  "$aw+$td+$hw", "SweepVectorZ:=", "0um")oEditor.Subtract Array("NAME:Selections", "Blank Parts:=", "diel_1", "Tool Parts:=",  _  "Pos_gnd_2"), Array("NAME:SubtractParameters", "KeepOriginals:=", true)oEditor.Subtract Array("NAME:Selections", "Blank Parts:=", "Univers", "Tool Parts:=",  _  "Pos_sig,Pos_gnd,Pos_gnd_2,diel_1"), Array("NAME:SubtractParameters", "KeepOriginals:=",  _  true)
